### ISSUE TITLE
Installation cannot be done on local host

### ISSUE THREAD

**Issue by jayabie** [fresns/fresns#7]
I'm trying to install fresns on localhost, but when i'm trying to jump to next step after selecting the language, the button is not working.
please advise.

![image](https://user-images.githubusercontent.com/44237013/230895408-b016ccc9-9488-4964-a873-7011232b732b.png)

**Comment by jevantang** [comment]
Please provide the Fresns version, browser and edition, preferably using the F12 developer tool to view and provide a log.

**Comment by jayabie** [comment]
Fresns Version: v2.7.2 [Latest] - Downloaded few days ago.
Browser: Edge, updated.
A screenshot attached of the console.
![image](https://user-images.githubusercontent.com/44237013/231540894-805a2165-30aa-4183-96bb-a036aab40d2a.png)

**Comment by jevantang** [comment]
It looks like your browser is not loading Alpine JS correctly.

Is your browser version up to date?

We've now released [Fresns v2.8](https://fresns.org/guide/install.html#download), so you can try again, but if that doesn't work, you'll have to wait for the next version of Alpine JS to be replaced by jQuery.

**Comment by jayabie** [comment]
My Edge browser is update to date.

The issue is still
see the log.
[localhost-1681574481523.log](https://github.com/fresns/fresns/files/11239958/localhost-1681574481523.log)

**Comment by jevantang** [comment]
I'm using the jQuery schema to refactor the install function, but it will take some time, you can try again with another browser, like Chrome

**Comment by jayabie** [comment]
I downloaded the last package, and during composer installation I'm getting this error.

![image](https://user-images.githubusercontent.com/44237013/232890722-3359411b-9e8f-4fb2-bfe0-59039f923af6.png)

**Comment by jevantang** [comment]
Please download the release version for installation and do not use the development library.

**Comment by jayabie** [comment]
Please advise how i can not use the development library any command that i should use?

**Comment by jevantang** [comment]
Option 1: Download the full package manually
https://fresns.org/guide/install.html#download

Option 2: Download via Composer
`composer create-project fresns/fresns`

**Comment by jayabie** [comment]
I did follow your instructions, now even the wizard is not starting.
![image](https://user-images.githubusercontent.com/44237013/234073602-ea4b1bca-3c4a-426b-badc-57e6bd358457.png)

**Comment by jevantang** [comment]
Please try using Chrome.
Also, what environment are you in and is it your environment configuration that is not loading the Laravel asset files.

**Comment by jayabie** [comment]
I'm using XAMPP with php8.
windows 10 and google chrome.

**Comment by jevantang** [comment]
> I'm using XAMPP with php8. windows 10 and google chrome.

I haven't used XAMPP before, but I will test the environment if I have time the day after tomorrow.
Also, are you using PHP version 8.1 or 8.2 - Fresns does not support versions 8.0 and below.

**Comment by jayabie** [comment]
I will try to upgrade my PHP to 8.1 or 8.2 and test again.

**Comment by jayabie** [comment]
> > I'm using XAMPP with php8. windows 10 and google chrome.
> 
> I haven't used XAMPP before, but I will test the environment if I have time the day after tomorrow. Also, are you using PHP version 8.1 or 8.2 - Fresns does not support versions 8.0 and below.

I did upgrade the PHP to 8.2, but the issue is still.
the wizard is not starting.

**Comment by jayabie** [comment]
no update on this @jevantang

**Comment by Temian1** [comment]
i also face this issue
